CREATE TABLE IF NOT EXISTS users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name  VARCHAR(255) NOT NULL,
    email VARCHAR(512) NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id),
    CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS locations
(
    id  BIGINT GENERATED BY DEFAULT AS IDENTITY,
    lat FLOAT NOT NULL,
    lon FLOAT NOT NULL,
    CONSTRAINT pk_location PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS categories
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL,
    CONSTRAINT pk_category PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS events
(
    annotation         VARCHAR(1024) NOT NULL,
    category_id        BIGINT        NOT NULL REFERENCES categories (id),
    confirmed_requests BIGINT,
    created_on         TIMESTAMP WITHOUT TIME ZONE,
    description        VARCHAR(1024) NOT NULL,
    event_date         TIMESTAMP WITHOUT TIME ZONE,
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY,
    initiator_id       BIGINT        NOT NULL REFERENCES users (id),
    location_id        BIGINT        NOT NULL REFERENCES locations (id),
    paid               BOOLEAN       NOT NULL,
    participant_limit  BIGINT,
    published_on       TIMESTAMP WITHOUT TIME ZONE,
    request_moderation BOOLEAN,
    state              VARCHAR(64),
    title              VARCHAR(128)  NOT NULL,
    views              BIGINT,
    CONSTRAINT pk_event PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS requests
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY,
    status       VARCHAR(255) NOT NULL,
    requester_id BIGINT       NOT NULL REFERENCES users (id),
    created      TIMESTAMP WITHOUT TIME ZONE,
    event_id     BIGINT REFERENCES events (id),
    CONSTRAINT pk_request PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS compilations
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY,
    pinned BOOLEAN,
    title  VARCHAR(128) NOT NULL,
    CONSTRAINT pk_compilation PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS events_compilation
(
    event_id       BIGINT REFERENCES events (id),
    compilation_id BIGINT REFERENCES compilations (id),
    CONSTRAINT uq_event_compilation UNIQUE (event_id, compilation_id)
);

CREATE TABLE IF NOT EXISTS comments
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY,
    text           VARCHAR                     NOT NULL,
    commentator_id BIGINT                      NOT NULL REFERENCES users (id),
    created_on     TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_comment PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS event_comments
(
    event_id   BIGINT REFERENCES events (id),
    comment_id BIGINT REFERENCES comments (id),
    CONSTRAINT uq_event_comment UNIQUE (event_id, comment_id)
);

DELETE
FROM events_compilation;
DELETE
FROM  event_comments;
DELETE
FROM comments;
DELETE
FROM compilations;
DELETE
FROM requests;
DELETE
FROM events;
DELETE
FROM categories;
DELETE
FROM locations;
DELETE
FROM users;
ALTER SEQUENCE comments_id_seq RESTART WITH 1;
ALTER SEQUENCE events_id_seq RESTART WITH 1;
ALTER SEQUENCE users_id_seq RESTART WITH 1;
ALTER SEQUENCE locations_id_seq RESTART WITH 1;
ALTER SEQUENCE categories_id_seq RESTART WITH 1;
ALTER SEQUENCE requests_id_seq RESTART WITH 1;
ALTER SEQUENCE compilations_id_seq RESTART WITH 1;