CREATE TABLE IF NOT EXISTS hits
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    app        VARCHAR(1024)               NOT NULL,
    uri        VARCHAR(1024)               NOT NULL,
    ip         VARCHAR(1024)               NOT NULL,
    times_tamp TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_hit PRIMARY KEY (id)
);